# Generated by Django 5.2.7 on 2025-10-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_modificaca',
            new_name='data_modificacao',
        ),
    ]
